FROM node:18-slim AS builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY services/websocket/package.json services/websocket/
RUN pnpm install --frozen-lockfile

COPY tsconfig.base.json ./
COPY services/websocket ./services/websocket
WORKDIR /app/services/websocket
RUN pnpm run build

FROM node:18-slim AS runtime

WORKDIR /app
COPY --from=builder /app/services/websocket/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/services/websocket/package.json ./

CMD ["node", "dist/index.js"]

EXPOSE 3002